### ISSUE TITLE
React の導入

### ISSUE THREAD

**Issue by 3846masa** [MiyashitaLab/miyashita.com#10]
React を導入して、スタイルを当てやすくしたい

-------

- [x] Jekyll から JSON を吐かせる
  - なんとかなりそう
- [x] React に Jekyll の JSON を渡す
  - `<script type="application/json" id="jekyll-data">` な感じで HTML に埋め込んどく
  - 遷移するときは HTML を `fetch` して DOM パースする
- [x] SSR っぽくする
  - `renderToString` でプレレンダリングしておく
  - プレレンダリングしたやつは Jekyll 経由で JSON が埋め込まれるようにする
- [x] Hot Module Replacement したい
  - Jekyll と dev-server の連携が悩みどころ

-----------

**TODO**

- [ ] **以下の項目を適宜 issue にする**
- [x] news.miyashita.com を miyashita.com に統合
    - URL 的には分けた方が見栄えがいいけど，デメリットが多いのでやめる
- [x] `MarkdownContent` の画像サイズを調整
    - `width: 100%` とかにしとけばいいのか？
- [x] #11 News 画面を作る -> @pvcresin に相談したい
    - こういう感じにしたい https://www.blog.google/
    - [x] News 一覧
    - [x] News 記事ページ
- [x] エラーページ
- [x] リダイレクトページ
  - https://www.netlify.com/docs/redirects/ を使うのもアリか？
- [ ] #12 各ページに編集画面へのリンクボタンを置く
    - https://miyashita-lab.slack.com/archives/C2VRT19JP/p1509329013000149
- [x] SNS ボタン
- [x] meta データ
    - [x] Title
    - [x] Twitter Card
    - [x] Facebook OGP
- [ ] 画像を Google Photos に移行
    - 適当なアルバムに全部突っ込んで URL 書き換える
- [x] ServiceWorker でキャッシュさせたい
    - https://github.com/goldhand/sw-precache-webpack-plugin とか？
- [ ] #13 https://github.com/miya0001/Front-End-Checklist に準拠させる

**Comment by 3846masa** [comment]
https://github.com/MiyashitaLab/miyashita.com/tree/use-react でベースを作った
clone して試してみて

@mimorisuzuko @pvcresin

**Comment by 3846masa** [comment]
React-static にして Jekyll を除いた
https://github.com/MiyashitaLab/miyashita.com/tree/react-static

**Comment by 3846masa** [comment]
GitHub Pages だけで頑張るのはやめて，Netlify を使うことにしたので， Node.js だけで良くなった

**Comment by 3846masa** [comment]
研究室サイトの dev.to を目指した高速化をしたい～

**Comment by 3846masa** [comment]
React をやめて Vue にした See #15.

**Comment by 3846masa** [comment]
Netlify CMS が React だったので React Static で再実装した
