### ISSUE TITLE
Vue の導入

### ISSUE THREAD

**Issue by 3846masa** [MiyashitaLab/miyashita.com#15]
正直 React でも良かったんだけど，以下の点から Vue に変更

- React 自体が大きい
- 今後の引き継ぎを考えると，JSX 記法 より template 記法のほうが学習コストが低そう

-----------
**TODO**

- [x] news.miyashita.com を miyashita.com に統合
    - news.miyashita.com は miyashita.com/news/ にリダイレクト
    - Cloudflare のリダイレクト機能を使う
- [ ] #12 各ページに編集画面へのリンクボタンを置く
    - https://miyashita-lab.slack.com/archives/C2VRT19JP/p1509329013000149
- [ ] 画像を Google Photos に移行
    - 適当なアルバムに全部突っ込んで URL 書き換える
- [ ] #13 https://github.com/miya0001/Front-End-Checklist に準拠させる

**Comment by 3846masa** [comment]
Netlify CMS 導入のため，やっぱり React Static にした
